#!/system/bin/sh

# Sync to data in the rare case a device crashes
sync

# Push Notification
su -lp 2000 -c "/system/bin/cmd notification post -t 'Encore Tweaks' -i file:///data/local/tmp/encore_logo.png -I file:///data/local/tmp/encore_logo.png 'encore$(date +%s)' 'Tweaks successfully applied'" >/dev/null &

apply() {
	if [ -f $2 ]; then
		chmod 644 $2 >/dev/null 2>&1
		echo $1 >$2 2>/dev/null
		chmod 444 $2 >/dev/null 2>&1
	fi
}

# I/O Tweaks
for queue in /sys/block/mmcblk0/queue /sys/block/mmcblk1/queue /sys/block/sd*/queue; do
	# Disable I/O statistics accounting
	apply 0 "$queue/iostats"

	# Don't use I/O as source of randomness
	apply 0 "$queue/add_random"
done &

# Networking tweaks
if grep -q bbr2 /proc/sys/net/ipv4/tcp_available_congestion_control; then
	apply "bbr2" /proc/sys/net/ipv4/tcp_congestion_control
else
	apply "cubic" /proc/sys/net/ipv4/tcp_congestion_control
fi

apply "1" /proc/sys/net/ipv4/tcp_low_latency
apply "1" /proc/sys/net/ipv4/tcp_ecn
apply "3" /proc/sys/net/ipv4/tcp_fastopen
apply "1" /proc/sys/net/ipv4/tcp_sack
apply "0" /proc/sys/net/ipv4/tcp_timestamps
apply "0" /proc/sys/net/ipv4/tcp_syncookies

# Disable ccci debugging
apply 0 /sys/kernel/ccci/debug

# Stop tracing and debugging
apply 0 /sys/kernel/tracing/tracing_on
apply 0 /proc/sys/kernel/perf_event_paranoid
apply 0 /proc/sys/kernel/debug_locks
apply 0 /proc/sys/kernel/perf_cpu_time_max_percent
apply off /proc/sys/kernel/printk_devkmsg

# Kill logd
encore-utils kill_logd

# Disable schedstats
apply 0 /proc/sys/kernel/sched_schedstats

# Disable Sched auto group
apply 0 /proc/sys/kernel/sched_autogroup_enabled

# Enable CRF
apply 1 /proc/sys/kernel/sched_child_runs_first

# Improve real time latencies by reducing the scheduler migration time
apply 32 /proc/sys/kernel/sched_nr_migrate

# Tweaking scheduler to reduce latency
apply 50000 /proc/sys/kernel/sched_migration_cost_ns
apply 1000000 /proc/sys/kernel/sched_min_granularity_ns
apply 1500000 /proc/sys/kernel/sched_wakeup_granularity_ns

# Disable read-ahead for swap devices
apply 0 /proc/sys/vm/page-cluster

# Update /proc/stat less often to reduce jitter
apply 120 /proc/sys/vm/stat_interval

# Disable compaction_proactiveness
apply 0 /proc/sys/vm/compaction_proactiveness

# Disable SPI CRC
apply 0 /sys/module/mmc_core/parameters/use_spi_crc

# Disable OnePlus opchain
apply 0 /sys/module/opchain/parameters/chain_on

# Disable Oplus bloats
apply 0 /sys/module/cpufreq_bouncing/parameters/enable
apply 0 /proc/task_info/task_sched_info/task_sched_info_enable
apply 0 /proc/oplus_scheduler/sched_assist/sched_assist_enabled

# Report max CPU capabilities to these libraries
apply "libunity.so, libil2cpp.so, libmain.so, libUE4.so, libgodot_android.so, libgdx.so, libgdx-box2d.so, libminecraftpe.so, libLive2DCubismCore.so, libyuzu-android.so, libryujinx.so, libcitra-android.so, libhdr_pro_engine.so, libandroidx.graphics.path.so, libeffect.so" /proc/sys/kernel/sched_lib_name
apply 255 /proc/sys/kernel/sched_lib_mask_force

wait
exit 0
