#!/system/bin/sh

get_module_version() {
	grep "version=" /data/adb/modules/encore/module.prop | awk -F'=' '{print $2}'
}

get_service_state() {
	if ps -e | grep encore-service >/dev/null; then
		echo "1"
	else
		echo "0"
	fi
}

get_service_pid() {
	pidof -s encore-service || echo null
}

get_chipset() {
	getprop "ro.board.platform"
}

get_kernel() {
	uname -r
}

get_default_cpugov() {
	if [ -f /data/encore/custom_default_cpu_gov ]; then
		cat /data/encore/custom_default_cpu_gov
	else
		cat /data/encore/default_cpu_gov
	fi
}

get_perf_cpugov() {
	cat /data/encore/perf_cpu_gov
}

get_available_cpugov() {
	chmod 644 /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
	cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
}

set_default_cpugov() {
	echo $1 >/data/encore/custom_default_cpu_gov
}

set_perf_cpugov() {
	echo $1 >/data/encore/perf_cpu_gov
}

get_kill_logd() {
	cat /data/encore/kill_logd
}

kill_logd() {
	list_logger="
logd
traced
statsd
tcpdump
cnss_diag
subsystem_ramdump
charge_logger
wlan_logging
"

	for svc in $list_logger; do
		if [ "$(cat /data/encore/kill_logd)" -eq 1 ]; then
			stop $svc 2>/dev/null
		else
			start $svc 2>/dev/null
		fi
	done
}

set_kill_logd() {
	echo $1 >/data/encore/kill_logd
	kill_logd
}

restart_service() {
	pkill encore-service
	su -c "encore-service" </dev/null >/dev/null 2>&1 &
}

get_gamelist() {
	cat /data/encore/gamelist.txt
}

save_gamelist() {
	echo "$1" | tr '/' '|' >/data/encore/gamelist.txt
}

save_logs() {
	logfile="/sdcard/encore_log"
	cat <<EOF >$logfile
*****************************************************
Encore Tweaks Log

Version: $(get_module_version)
Chipset: $(get_chipset)
Kernel Version: $(get_kernel)
*****************************************************

$(cat /data/encore/encore_log)
EOF
}

eval "$1 $2"
