#!/system/bin/sh

sync

last_gamepreloaded="/data/encore/last_gamepreloaded"

gameCache=(
	"cache/vulkan_pso_cache.bin"
	"cache/UnityShaderCache"
	"files/ProgramBinaryCache"
)

grapicLibs=(
	"libGLESv1_CM.so"
	"libGLESv2.so"
	"libGLESv3.so"
	"libvulkan.so"
	"libskia.so"
	"libEGL.so"
	"libgsl.so"
	"libRS.so"
	"libsurfaceflinger.so"
	"hw/vulkan.adreno.so"
	"egl/libGLES_mali.so"
	"egl/libEGL_powervr.so"
	"egl/libEGL_adreno.so"
	"egl/libGLESv1_CM_adreno.so"
	"egl/libGLESv2_adreno.so"
	"egl/libGLESv1_CM_powervr.so"
	"egl/libGLESv2_powervr.so"
)

libsPath=(
	"/system/lib"
	"/system/lib64"
	"/vendor/lib"
	"/vendor/lib64"
)

preloadGraphicLibs() {
	echo 3 >/proc/sys/vm/drop_caches
	for lib in ${grapicLibs[@]}; do
		for path in ${libsPath[@]}; do
			if [ -f $path/$lib ]; then
				su -c vmtouch -f -Ld $path/$lib
			fi
		done
	done
}

evictGraphicLibs() {
	for lib in ${grapicLibs[@]}; do
		for path in ${libsPath[@]}; do
			if [ -f $path/$lib ]; then
				pkill -f "vmtouch -f -Ld $path/$lib"
				vmtouch -f -e $path/$lib
			fi
		done
	done
	echo 3 >/proc/sys/vm/drop_caches
}

preloadGameStuff() {
	echo 3 >/proc/sys/vm/drop_caches
	echo "$1" >$last_gamepreloaded
	appDir=$(dirname $(pm path $1 | head -n 1 | cut -d: -f2))
	for cache in ${gameCache[@]}; do
		if [ -f /sdcard/Android/data/$1/$cache ] || [ -d /sdcard/Android/data/$1/$cache ]; then
			su -c vmtouch -Ld /sdcard/Android/data/$1/$cache
		fi
	done
	[ -f $appDir/base.apk ] && su -c vmtouch -Ld $appDir/base.apk
	[ -f $appDir/split_config.arm64_v8a.apk ] && su -c vmtouch -Ld $appDir/split_config.arm64_v8a.apk
	[ -f $appDir/split_config.armeabi-v7a.apk ] && su -c vmtouch -Ld $appDir/split_config.armeabi-v7a.apk
}

evictGameStuff() {
	local game=$(cat $last_gamepreloaded)
	appDir=$(dirname $(pm path $game | head -n 1 | cut -d: -f2))
	for cache in ${gameCache[@]}; do
		if [ -f /sdcard/Android/data/$game/$cache ] || [ -d /sdcard/Android/data/$game/$cache ]; then
			pkill -f "vmtouch -Ld /sdcard/Android/data/$game/$cache"
			vmtouch -e /sdcard/Android/data/$game/$cache
		fi
	done
	[ -f $appDir/base.apk ] && pkill -f "vmtouch -Ld $appDir/base.apk" && vmtouch -e $appDir/base.apk
	[ -f $appDir/split_config.arm64_v8a.apk ] && pkill -f "vmtouch -Ld $appDir/split_config.arm64_v8a.apk" && vmtouch -e $appDir/split_config.arm64_v8a.apk
	[ -f $appDir/split_config.armeabi-v7a.apk ] && pkill -f "vmtouch -Ld $appDir/split_config.armeabi-v7a.apk" && vmtouch -e $appDir/split_config.armeabi-v7a.apk
	echo 3 >/proc/sys/vm/drop_caches
}

case "$1 $2" in
"1 1") preloadGraphicLibs ;;
"1 0") evictGraphicLibs ;;
"2 1") [ ! -z "$3" ] && [ $(cat /data/encore/preload_game) -eq 1 ] && preloadGameStuff "$3" ;;
"2 0") [ $(cat /data/encore/preload_game) -eq 1 ] && evictGameStuff ;;
esac
