#!/system/bin/sh

[ -z $DEV_ENV ] && set +x

get_module_version() {
	grep "version=" /data/adb/modules/encore/module.prop | awk -F'=' '{print $2}'
}

get_service_state() {
	if ps -e | grep encored >/dev/null; then
		echo "1"
	else
		echo "0"
	fi
}

get_service_pid() {
	pidof -s encored || echo null
}

get_chipset() {
	getprop "ro.board.platform"
}

get_kernel() {
	uname -r
}

get_default_cpugov() {
	if [ -f /data/encore/custom_default_cpu_gov ]; then
		cat /data/encore/custom_default_cpu_gov
	else
		cat /data/encore/default_cpu_gov
	fi
}

get_perf_cpugov() {
	cat /data/encore/perf_cpu_gov
}

get_powersave_cpugov() {
	cat /data/encore/powersave_cpu_gov
}

get_available_cpugov() {
	chmod 644 /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
	cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
}

set_default_cpugov() {
	echo $1 >/data/encore/custom_default_cpu_gov
}

set_perf_cpugov() {
	echo $1 >/data/encore/perf_cpu_gov
}

set_powersave_cpugov() {
	echo $1 >/data/encore/powersave_cpu_gov
}

get_kill_logd() {
	cat /data/encore/kill_logd
}

kill_logd() {
	list_logger="
logd
traced
statsd
tcpdump
cnss_diag
subsystem_ramdump
charge_logger
wlan_logging
"

	for svc in $list_logger; do
		if [ "$(cat /data/encore/kill_logd)" -eq 1 ]; then
			stop $svc 2>/dev/null
		else
			start $svc 2>/dev/null
		fi
	done
}

set_kill_logd() {
	echo $1 >/data/encore/kill_logd
	kill_logd
}

restart_service() {
	pkill encored
	su -c "encored" </dev/null >/dev/null 2>&1 &
}

get_gamelist() {
	cat /data/encore/gamelist.txt
}

save_gamelist() {
	echo "$1" | tr '/' '|' >/data/encore/gamelist.txt
}

open_website() {
	/system/bin/am start -a android.intent.action.VIEW -d "https://encore.rem01gaming.dev/" >/dev/null
}

warn_drm_failed() {
	/system/bin/am start -a android.intent.action.VIEW -d "https://encore.rem01gaming.dev/" >/dev/null
	su -lp 2000 -c "/system/bin/cmd notification post -t 'Encore Tweaks' 'encore' 'DRM Check failed, please re-install Encore Tweaks from official website encore.rem01gaming.dev.'" >/dev/null
}

save_logs() {
	cat <<EOF >/sdcard/encore_log
*****************************************************
Encore Tweaks Log

Version: $(get_module_version)
Chipset: $(get_chipset)
Kernel Version: $(get_kernel)
*****************************************************

$(cat /data/encore/encore_log)
EOF
}

get_profile() {
	cat /dev/encore_mode
}

[ -d /data/adb/modules/encore ] || warn_drm_failed
$@
