// Add your translation here, use ISO 639-1 standard for IDs
const translations = {
  en: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Current Profile",
    kernelTitle: "Kernel",
    chipsetTitle: "Chipset",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Settings",
    killLogger: "Kill Logger",
    dndGameplay: "DND on Gameplay",
    defaultCpuGov: "Default CPU Governor",
    powersaveCpuGov: "Powersave CPU Governor",
    actionsTitle: "Actions",
    supportTitle: "Support Me",
    supportDescription: "Encore Tweaks is, and always will be, free for you, and everyone. You can however show me that you care by making a donation.",
    killLoggerTitle: "Kill Logger",
    killLoggerDesc: "This option will stop the logger services and silence logs, enabling a reduction in performance overhead.",
    killLoggerWarning: "WARNING: Software that depends on the logd service will not work properly!",
    dndTitle: "Do Not Disturb",
    dndDesc: "Enable do not disturb mode when playing games. Limits interruptions from notifications and calls, allowing you to play your favorite games without any distraction.",
    permissionDeniedTitle: "Permission Denied",
    permissionDeniedDesc: "Please activate the JavaScript API for Encore Tweaks in MMRL settings; this WebUI will not function without it.",
    breadcrumbsSettings: "Settings",
    breadcrumbsModules: "Modules & Permissions",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Allow Advanced KernelSU API",
    editGamelistTitle: "Edit Gamelist",
    editGamelistDesc: "The performance profile will be activated when any of the games and apps listed here are launched.",
    saveChanges: "Save Changes",
    cancelChanges: "Cancel Changes",
    saveLogs: "Save Module Logs"
  },
  id: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Profil saat ini",
    kernelTitle: "Kernel",
    chipsetTitle: "Chipset",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Pengaturan",
    killLogger: "Hentikan Logger",
    dndGameplay: "DND Saat Bermain",
    defaultCpuGov: "CPU Governor Default",
    powersaveCpuGov: "CPU Governor Hemat Daya",
    actionsTitle: "Aksi",
    supportTitle: "Dukung Saya",
    supportDescription: "Encore Tweaks akan selalu gratis untuk semua orang. Namun Anda dapat menunjukkan kepedulian Anda dengan memberikan donasi.",
    killLoggerTitle: "Hentikan Logger",
    killLoggerDesc: "Pilihan ini akan menghentikan layanan pencatat dan membungkam log, sehingga mengurangi overhead kinerja.",
    killLoggerWarning: "PERINGATAN: Perangkat lunak yang bergantung pada layanan logd tidak akan berfungsi dengan baik!",
    dndTitle: "Mode Jangan Ganggu",
    dndDesc: "Aktifkan mode jangan ganggu saat bermain game. Batasi gangguan dari notifikasi dan panggilan, sehingga Anda dapat memainkan game favorit tanpa gangguan apa pun.",
    permissionDeniedTitle: "Izin Ditolak",
    permissionDeniedDesc: "Harap aktifkan JavaScript API untuk Encore Tweaks di pengaturan MMRL; WebUI ini tidak akan berfungsi tanpanya.",
    breadcrumbsSettings: "Pengaturan",
    breadcrumbsModules: "Modul & Perizinan",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Izinkan API KernelSU Lanjutan",
    editGamelistTitle: "Edit Daftar Permainan",
    editGamelistDesc: "Profil kinerja akan diaktifkan ketika salah satu permainan dan aplikasi yang tercantum di sini diluncurkan.",
    saveChanges: "Simpan Perubahan",
    cancelChanges: "Batalkan Perubahan",
    saveLogs: "Simpan Log Modul"
  },
  jv: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Profil Saiki",
    kernelTitle: "Kernel",
    chipsetTitle: "Chipset",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Setelan",
    killLogger: "Mateni Logger",
    dndGameplay: "DND nalika Main",
    defaultCpuGov: "Gubernur CPU Gawan",
    powersaveCpuGov: "Gubernur CPU Irit Daya",
    actionsTitle: "Tindakan",
    supportTitle: "Dukung Aku",
    supportDescription: "Encore Tweaks gratis lan bakal tetep gratis kanggo sapa wae. Nanging, sampeyan bisa nuduhake rasa peduli kanthi nyumbang.",
    killLoggerTitle: "Mateni Logger",
    killLoggerDesc: "Opsi iki bakal mateni layanan logger lan ngedohake log, nyuda beban kinerja.",
    killLoggerWarning: "PERHATIAN: Piranti lunak sing gumantung karo layanan logd bisa uga ora bisa mlaku kanthi bener!",
    dndTitle: "Ora Gangguan",
    dndDesc: "Aktifake mode ora gangguan nalika dolanan game. Ngalang-alangi notifikasi lan telpon supaya sampeyan bisa fokus dolanan tanpa gangguan.",
    permissionDeniedTitle: "Ijin Ditolak",
    permissionDeniedDesc: "Mangga aktifake API JavaScript kanggo Encore Tweaks ing setelan MMRL; WebUI iki ora bakal bisa tanpa iku.",
    breadcrumbsSettings: "Setelan",
    breadcrumbsModules: "Modul & Ijin",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Ijini API KernelSU Lanjutan",
    editGamelistTitle: "Sunting Dhaptar Game",
    editGamelistDesc: "Profil kinerja bakal diaktifake nalika game utawa aplikasi sing kadhaptar ing kene dibukak.",
    saveChanges: "Simpen Owahan",
    cancelChanges: "Batalake Owahan",
    saveLogs: "Simpen Log Modul"
  },
  da: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Aktuel Profil",
    kernelTitle: "Kernel",
    chipsetTitle: "Chipset",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Indstillinger",
    killLogger: "Deaktivér Logger",
    dndGameplay: "Forstyr ikke under spil",
    defaultCpuGov: "Standard CPU Governor",
    powersaveCpuGov: "Energibesparende CPU Governor",
    actionsTitle: "Handlinger",
    supportTitle: "Støt Mig",
    supportDescription: "Encore Tweaks er og vil altid være gratis for alle. Du kan dog vise din støtte ved at donere.",
    killLoggerTitle: "Slå Logger Fra",
    killLoggerDesc: "Denne mulighed stopper logningstjenesterne og slår loggene fra, hvilket reducerer ydelsesoverhead.",
    killLoggerWarning: "ADVARSEL: Software, der afhænger af logd-tjenesten, fungerer muligvis ikke korrekt!",
    dndTitle: "Forstyr ikke",
    dndDesc: "Aktiver 'Forstyr ikke'-tilstand under spil. Begrænser forstyrrelser fra notifikationer og opkald, så du kan spille uden afbrydelser.",
    permissionDeniedTitle: "Adgang nægtet",
    permissionDeniedDesc: "Aktiver venligst JavaScript API for Encore Tweaks i MMRL-indstillingerne; denne WebUI fungerer ikke uden det.",
    breadcrumbsSettings: "Indstillinger",
    breadcrumbsModules: "Moduler & Tilladelser",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Tillad Avanceret KernelSU API",
    editGamelistTitle: "Rediger Spilleliste",
    editGamelistDesc: "Ydelsesprofilen aktiveres, når et af spillene eller appsene på denne liste startes.",
    saveChanges: "Gem ændringer",
    cancelChanges: "Annuller ændringer",
    saveLogs: "Gem Modul-Logger"
  },
  pt: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Perfil Atual",
    kernelTitle: "Kernel",
    chipsetTitle: "Chipset",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Configurações",
    killLogger: "Desativar Logger",
    dndGameplay: "DND no Jogo",
    defaultCpuGov: "Governador Padrão da CPU",
    powersaveCpuGov: "Governador de CPU Economia de Energia",
    actionsTitle: "Ações",
    supportTitle: "Apoie-me",
    supportDescription: "O Encore Tweaks é e sempre será gratuito para você e todos. No entanto, você pode demonstrar seu apoio fazendo uma doação.",
    killLoggerTitle: "Desativar Logger",
    killLoggerDesc: "Esta opção interromperá os serviços de log e silenciará os registros, reduzindo a sobrecarga de desempenho.",
    killLoggerWarning: "AVISO: Softwares que dependem do serviço logd podem não funcionar corretamente!",
    dndTitle: "Não Perturbe",
    dndDesc: "Ativar o modo 'Não Perturbe' ao jogar. Isso limita interrupções de notificações e chamadas, permitindo que você jogue sem distrações.",
    permissionDeniedTitle: "Permissão Negada",
    permissionDeniedDesc: "Ative a API JavaScript para o Encore Tweaks nas configurações do MMRL; esta WebUI não funcionará sem isso.",
    breadcrumbsSettings: "Configurações",
    breadcrumbsModules: "Módulos e Permissões",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Permitir API Avançada do KernelSU",
    editGamelistTitle: "Editar Lista de Jogos",
    editGamelistDesc: "O perfil de desempenho será ativado quando qualquer um dos jogos e aplicativos listados aqui for iniciado.",
    saveChanges: "Salvar Alterações",
    cancelChanges: "Cancelar Alterações",
    saveLogs: "Salvar Logs do Módulo"
  },
  tr: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Mevcut Profil",
    kernelTitle: "Kernel",
    chipsetTitle: "Yonga Seti",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Ayarlar",
    killLogger: "Günlük Kaydını Kapat",
    dndGameplay: "Oyun Sırasında DND",
    defaultCpuGov: "Varsayılan CPU Yöneticisi",
    powersaveCpuGov: "Güç Tasarrufu CPU Yöneticisi",
    actionsTitle: "Eylemler",
    supportTitle: "Beni Destekle",
    supportDescription: "Encore Tweaks her zaman ücretsiz olacak. Ancak, bağış yaparak desteğinizi gösterebilirsiniz.",
    killLoggerTitle: "Günlük Kaydını Kapat",
    killLoggerDesc: "Bu seçenek, günlük kaydı hizmetlerini durdurur ve günlükleri susturur, böylece performans yükünü azaltır.",
    killLoggerWarning: "UYARI: logd servisine bağlı yazılımlar düzgün çalışmayabilir!",
    dndTitle: "Rahatsız Etme",
    dndDesc: "Oyun oynarken 'Rahatsız Etmeyin' modunu etkinleştirir. Bildirimleri ve aramaları sınırlandırarak kesintisiz oyun deneyimi sağlar.",
    permissionDeniedTitle: "İzin Reddedildi",
    permissionDeniedDesc: "Encore Tweaks için JavaScript API'yi MMRL ayarlarında etkinleştirin; aksi takdirde bu WebUI çalışmaz.",
    breadcrumbsSettings: "Ayarlar",
    breadcrumbsModules: "Modüller ve İzinler",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Gelişmiş KernelSU API İzni",
    editGamelistTitle: "Oyun Listesini Düzenle",
    editGamelistDesc: "Burada listelenen oyunlar veya uygulamalar başlatıldığında performans profili etkinleştirilecektir.",
    saveChanges: "Değişiklikleri Kaydet",
    cancelChanges: "Değişiklikleri İptal Et",
    saveLogs: "Modül Günlüklerini Kaydet"
  },
  fr: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Profil Actuel",
    kernelTitle: "Kernel",
    chipsetTitle: "Chipset",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Paramètres",
    killLogger: "Désactiver le Logger",
    dndGameplay: "DND en Jeu",
    defaultCpuGov: "Gouverneur CPU Par Défaut",
    powersaveCpuGov: "Gouverneur CPU Économie d'Énergie",
    actionsTitle: "Actions",
    supportTitle: "Soutenez-moi",
    supportDescription: "Encore Tweaks est et sera toujours gratuit pour tout le monde. Cependant, vous pouvez me montrer votre soutien en faisant un don.",
    killLoggerTitle: "Désactiver le Logger",
    killLoggerDesc: "Cette option arrête les services de journalisation et désactive les logs, réduisant ainsi la surcharge des performances.",
    killLoggerWarning: "AVERTISSEMENT : Les logiciels qui dépendent du service logd peuvent ne pas fonctionner correctement !",
    dndTitle: "Ne Pas Déranger",
    dndDesc: "Activez le mode 'Ne Pas Déranger' pendant que vous jouez. Cela limite les interruptions dues aux notifications et aux appels, vous permettant ainsi de jouer sans distraction.",
    permissionDeniedTitle: "Permission Refusée",
    permissionDeniedDesc: "Veuillez activer l'API JavaScript pour Encore Tweaks dans les paramètres MMRL ; cette interface Web ne fonctionnera pas sans cela.",
    breadcrumbsSettings: "Paramètres",
    breadcrumbsModules: "Modules et Permissions",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Autoriser l'API Avancée de KernelSU",
    editGamelistTitle: "Modifier la Liste des Jeux",
    editGamelistDesc: "Le profil de performance sera activé lorsque l'un des jeux ou applications listés ici sera lancé.",
    saveChanges: "Enregistrer les Modifications",
    cancelChanges: "Annuler les Modifications",
    saveLogs: "Enregistrer les Journaux du Module"
  },
  de: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Aktuelles Profil",
    kernelTitle: "Kernel",
    chipsetTitle: "Chipset",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Einstellungen",
    killLogger: "Logger Beenden",
    dndGameplay: "Nicht stören im Spiel",
    defaultCpuGov: "Standard-CPU-Governor",
    powersaveCpuGov: "Energiespar-CPU-Governor",
    actionsTitle: "Aktionen",
    supportTitle: "Unterstütze mich",
    supportDescription: "Encore Tweaks ist und wird immer kostenlos sein. Du kannst mich jedoch mit einer Spende unterstützen.",
    killLoggerTitle: "Logger Beenden",
    killLoggerDesc: "Diese Option stoppt die Logger-Dienste und deaktiviert die Protokollierung, wodurch die Leistung verbessert wird.",
    killLoggerWarning: "WARNUNG: Software, die den logd-Dienst benötigt, funktioniert möglicherweise nicht richtig!",
    dndTitle: "Nicht Stören",
    dndDesc: "Aktiviert den 'Nicht Stören'-Modus beim Spielen. Reduziert Unterbrechungen durch Benachrichtigungen und Anrufe, sodass du ungestört spielen kannst.",
    permissionDeniedTitle: "Zugriff Verweigert",
    permissionDeniedDesc: "Bitte aktiviere die JavaScript-API für Encore Tweaks in den MMRL-Einstellungen; diese WebUI funktioniert sonst nicht.",
    breadcrumbsSettings: "Einstellungen",
    breadcrumbsModules: "Module & Berechtigungen",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Erweiterte KernelSU-API aktivieren",
    editGamelistTitle: "Spieleliste Bearbeiten",
    editGamelistDesc: "Das Leistungsprofil wird aktiviert, wenn eines der hier aufgeführten Spiele oder Apps gestartet wird.",
    saveChanges: "Änderungen Speichern",
    cancelChanges: "Änderungen Abbrechen",
    saveLogs: "Modul-Logs Speichern"
  },
  it: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Profilo Attuale",
    kernelTitle: "Kernel",
    chipsetTitle: "Chipset",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Impostazioni",
    killLogger: "Disattiva Logger",
    dndGameplay: "DND in Gioco",
    defaultCpuGov: "Governor CPU Predefinito",
    powersaveCpuGov: "Governor CPU Risparmio Energetico",
    actionsTitle: "Azioni",
    supportTitle: "Supportami",
    supportDescription: "Encore Tweaks è e sarà sempre gratuito per tutti. Tuttavia, puoi dimostrare il tuo supporto facendo una donazione.",
    killLoggerTitle: "Disattiva Logger",
    killLoggerDesc: "Questa opzione interrompe i servizi di logging e disattiva i log, riducendo il carico sulle prestazioni.",
    killLoggerWarning: "ATTENZIONE: Il software che dipende dal servizio logd potrebbe non funzionare correttamente!",
    dndTitle: "Non Disturbare",
    dndDesc: "Attiva la modalità 'Non Disturbare' mentre giochi. Limita le interruzioni da notifiche e chiamate, permettendoti di giocare senza distrazioni.",
    permissionDeniedTitle: "Permesso Negato",
    permissionDeniedDesc: "Attiva l'API JavaScript per Encore Tweaks nelle impostazioni MMRL; questa WebUI non funzionerà senza di essa.",
    breadcrumbsSettings: "Impostazioni",
    breadcrumbsModules: "Moduli e Permessi",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Consenti API Avanzata di KernelSU",
    editGamelistTitle: "Modifica Lista Giochi",
    editGamelistDesc: "Il profilo prestazioni verrà attivato quando uno dei giochi o delle app elencati qui verrà avviato.",
    saveChanges: "Salva Modifiche",
    cancelChanges: "Annulla Modifiche",
    saveLogs: "Salva Log del Modulo"
  },
  nl: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Huidig Profiel",
    kernelTitle: "Kernel",
    chipsetTitle: "Chipset",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Instellingen",
    killLogger: "Logger Uitschakelen",
    dndGameplay: "DND tijdens Gamen",
    defaultCpuGov: "Standaard CPU Governor",
    powersaveCpuGov: "Energiezuinige CPU Governor",
    actionsTitle: "Acties",
    supportTitle: "Steun Mij",
    supportDescription: "Encore Tweaks is en blijft altijd gratis voor iedereen. Je kunt me echter steunen door een donatie te doen.",
    killLoggerTitle: "Logger Uitschakelen",
    killLoggerDesc: "Deze optie stopt de logging-services en schakelt logs uit, waardoor de prestaties worden verbeterd.",
    killLoggerWarning: "WAARSCHUWING: Software die afhankelijk is van de logd-service werkt mogelijk niet correct!",
    dndTitle: "Niet Storen",
    dndDesc: "Schakel de modus 'Niet Storen' in tijdens het gamen. Beperkt onderbrekingen door meldingen en oproepen, zodat je ongestoord kunt spelen.",
    permissionDeniedTitle: "Toestemming Geweigerd",
    permissionDeniedDesc: "Schakel de JavaScript-API voor Encore Tweaks in de MMRL-instellingen in; deze WebUI werkt anders niet.",
    breadcrumbsSettings: "Instellingen",
    breadcrumbsModules: "Modules & Machtigingen",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Geavanceerde KernelSU API Toestaan",
    editGamelistTitle: "Spellenlijst Bewerken",
    editGamelistDesc: "Het prestatieprofiel wordt geactiveerd wanneer een van de hier vermelde spellen of apps wordt gestart.",
    saveChanges: "Wijzigingen Opslaan",
    cancelChanges: "Wijzigingen Annuleren",
    saveLogs: "Module Logs Opslaan"
  },
  hu: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Aktuális Profil",
    kernelTitle: "Kernel",
    chipsetTitle: "Chipkészlet",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Beállítások",
    killLogger: "Logger leállítása",
    dndGameplay: "Ne zavarjanak játék közben",
    defaultCpuGov: "Alapértelmezett CPU Governor",
    powersaveCpuGov: "Energiatakarékos CPU Governor",
    actionsTitle: "Műveletek",
    supportTitle: "Támogass Engem",
    supportDescription: "Az Encore Tweaks mindig ingyenes lesz mindenki számára. Ha szeretnéd támogatni a munkámat, adományozhatsz.",
    killLoggerTitle: "Logger leállítása",
    killLoggerDesc: "Ez a lehetőség leállítja a naplózási szolgáltatásokat és elnémítja a naplókat, csökkentve a teljesítményterhelést.",
    killLoggerWarning: "FIGYELMEZTETÉS: A logd szolgáltatástól függő szoftverek nem működhetnek megfelelően!",
    dndTitle: "Ne zavarjanak",
    dndDesc: "Játék közben aktiválja a Ne zavarjanak módot. Korlátozza az értesítéseket és a hívásokat, lehetővé téve a zavartalan játékot.",
    permissionDeniedTitle: "Engedély megtagadva",
    permissionDeniedDesc: "Kérlek, engedélyezd a JavaScript API-t az Encore Tweaks számára az MMRL beállításaiban; enélkül ez a WebUI nem fog működni.",
    breadcrumbsSettings: "Beállítások",
    breadcrumbsModules: "Modulok és Engedélyek",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Haladó KernelSU API engedélyezése",
    editGamelistTitle: "Játékkönyvtár szerkesztése",
    editGamelistDesc: "A teljesítményprofil aktiválódik, amikor bármelyik játék vagy alkalmazás ezen a listán elindul.",
    saveChanges: "Változások mentése",
    cancelChanges: "Változások visszavonása",
    saveLogs: "Modul naplók mentése"
  },
  ms: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Profil Kini",
    kernelTitle: "Kernel",
    chipsetTitle: "Cipset",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Tetapan",
    killLogger: "Matikan Logger",
    dndGameplay: "Jangan Ganggu Semasa Bermain",
    defaultCpuGov: "Default CPU Governor",
    powersaveCpuGov: "CPU Governor Hemat Daya",
    actionsTitle: "Tindakan",
    supportTitle: "Sokong Saya",
    supportDescription: "Encore Tweaks sentiasa percuma untuk semua orang. Namun, anda boleh menunjukkan sokongan dengan membuat sumbangan.",
    killLoggerTitle: "Matikan Logger",
    killLoggerDesc: "Pilihan ini akan menghentikan perkhidmatan log dan menyenyapkan log, mengurangkan beban performa.",
    killLoggerWarning: "AMARAN: Perisian yang bergantung kepada perkhidmatan logd mungkin tidak berfungsi dengan betul!",
    dndTitle: "Jangan Ganggu",
    dndDesc: "Aktifkan mod Jangan Ganggu semasa bermain permainan. Menghadkan gangguan daripada notifikasi dan panggilan, membolehkan anda bermain tanpa gangguan.",
    permissionDeniedTitle: "Kebenaran Ditolak",
    permissionDeniedDesc: "Sila aktifkan API JavaScript untuk Encore Tweaks dalam tetapan MMRL; WebUI ini tidak akan berfungsi tanpanya.",
    breadcrumbsSettings: "Tetapan",
    breadcrumbsModules: "Modul & Kebenaran",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Benarkan API KernelSU Lanjutan",
    editGamelistTitle: "Sunting Senarai Permainan",
    editGamelistDesc: "Profil prestasi akan diaktifkan apabila mana-mana permainan atau aplikasi dalam senarai ini dilancarkan.",
    saveChanges: "Simpan Perubahan",
    cancelChanges: "Batal Perubahan",
    saveLogs: "Simpan Log Modul"
  },
  ru: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Текущий профиль",
    kernelTitle: "Kernel",
    chipsetTitle: "Чипсет",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Настройки",
    killLogger: "Остановить логгер",
    dndGameplay: "Не беспокоить во время игры",
    defaultCpuGov: "CPU Governor по умолчанию",
    powersaveCpuGov: "Энергосберегающий CPU Governor",
    actionsTitle: "Действия",
    supportTitle: "Поддержите меня",
    supportDescription: "Encore Tweaks всегда был и будет бесплатным для вас и для всех. Однако вы можете показать свою поддержку, сделав пожертвование.",
    killLoggerTitle: "Остановить логгер",
    killLoggerDesc: "Эта опция остановит службы логгера и отключит запись логов, что позволит снизить нагрузку на производительность.",
    killLoggerWarning: "ВНИМАНИЕ: Программное обеспечение, зависящее от службы logd, не будет работать должным образом!",
    dndTitle: "Не беспокоить",
    dndDesc: "Включает режим «Не беспокоить» во время игры, что ограничивает прерывания от уведомлений и звонков, позволяя вам наслаждаться любимыми играми без отвлекающих факторов.",
    permissionDeniedTitle: "Доступ запрещен",
    permissionDeniedDesc: "Пожалуйста, активируйте JavaScript API для Encore Tweaks в настройках MMRL; этот веб-интерфейс не будет работать без него.",
    breadcrumbsSettings: "Настройки",
    breadcrumbsModules: "Модули и разрешения",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Разрешить расширенный API KernelSU",
    editGamelistTitle: "Редактировать список игр",
    editGamelistDesc: "Профиль производительности будет активирован при запуске любой из указанных игр и приложений.",
    saveChanges: "Сохранить изменения",
    cancelChanges: "Отменить изменения",
    saveLogs: "Сохранить логи модуля"
  },
  ja: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "現在のプロファイル",
    kernelTitle: "Kernel",
    chipsetTitle: "チップセット",
    androidSDKTitle: "Android SDK",
    settingsTitle: "設定",
    killLogger: "ロガーを停止",
    dndGameplay: "プレイ中はおやすみモード",
    defaultCpuGov: "デフォルトのCPUガバナー",
    powersaveCpuGov: "省電力CPUガバナー",
    actionsTitle: "アクション",
    supportTitle: "サポートする",
    supportDescription: "Encore Tweaksは無料で提供されており、これからもそうです。ただし、寄付を通じてサポートを示すことができます。",
    killLoggerTitle: "ロガーを停止",
    killLoggerDesc: "このオプションはロガーサービスを停止し、ログを無効化します。これによりパフォーマンスのオーバーヘッドが削減されます。",
    killLoggerWarning: "警告: logdサービスに依存するソフトウェアは正常に動作しなくなります！",
    dndTitle: "おやすみモード",
    dndDesc: "ゲームをプレイ中におやすみモードを有効にします。通知や通話による中断を制限し、快適にゲームを楽しめます。",
    permissionDeniedTitle: "権限が拒否されました",
    permissionDeniedDesc: "Encore TweaksのJavaScript APIをMMRL設定で有効にしてください。有効でない場合、このWebUIは機能しません。",
    breadcrumbsSettings: "設定",
    breadcrumbsModules: "モジュールと権限",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "高度なKernelSU APIを許可",
    editGamelistTitle: "ゲームリストを編集",
    editGamelistDesc: "ここにリストされたゲームやアプリが起動すると、パフォーマンスプロファイルが有効になります。",
    saveChanges: "変更を保存",
    cancelChanges: "変更をキャンセル",
    saveLogs: "モジュールログを保存"
  },
  zh: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "当前配置文件",
    kernelTitle: "Kernel",
    chipsetTitle: "芯片组",
    androidSDKTitle: "Android SDK",
    settingsTitle: "设置",
    killLogger: "关闭日志",
    dndGameplay: "游戏时请勿打扰",
    defaultCpuGov: "默认CPU调控器",
    powersaveCpuGov: "省电CPU调控器",
    actionsTitle: "操作",
    supportTitle: "支持我",
    supportDescription: "Encore Tweaks 是免费的，并且将永远保持免费。但你可以通过捐赠来支持我。",
    killLoggerTitle: "关闭日志",
    killLoggerDesc: "启用此选项后，将停止日志服务并屏蔽日志，从而减少性能开销。",
    killLoggerWarning: "警告：依赖 logd 服务的软件可能无法正常运行！",
    dndTitle: "请勿打扰",
    dndDesc: "在玩游戏时启用请勿打扰模式。限制通知和电话的干扰，让你可以专心享受游戏。",
    permissionDeniedTitle: "权限拒绝",
    permissionDeniedDesc: "请在 MMRL 设置中启用 Encore Tweaks 的 JavaScript API，否则此 WebUI 将无法运行。",
    breadcrumbsSettings: "设置",
    breadcrumbsModules: "模块与权限",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "允许高级 KernelSU API",
    editGamelistTitle: "编辑游戏列表",
    editGamelistDesc: "当这里列出的游戏或应用启动时，将自动激活性能配置。",
    saveChanges: "保存更改",
    cancelChanges: "取消更改",
    saveLogs: "保存模块日志"
  },
  th: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "โปรไฟล์ปัจจุบัน",
    kernelTitle: "Kernel",
    chipsetTitle: "ชิปเซ็ต",
    androidSDKTitle: "Android SDK",
    settingsTitle: "การตั้งค่า",
    killLogger: "ปิด Logger",
    dndGameplay: "ห้ามรบกวนขณะเล่นเกม",
    defaultCpuGov: "โหมด CPU มาตรฐาน",
    powersaveCpuGov: "โหมดประหยัดพลังงาน CPU",
    actionsTitle: "การดำเนินการ",
    supportTitle: "สนับสนุนฉัน",
    supportDescription: "Encore Tweaks ให้บริการฟรีเสมอสำหรับทุกคน อย่างไรก็ตาม คุณสามารถแสดงการสนับสนุนได้โดยการบริจาค",
    killLoggerTitle: "ปิด Logger",
    killLoggerDesc: "ตัวเลือกนี้จะหยุดบริการบันทึกและปิดเสียงล็อก เพื่อลดภาระของประสิทธิภาพ",
    killLoggerWarning: "คำเตือน: ซอฟต์แวร์ที่ต้องใช้บริการ logd อาจทำงานไม่ถูกต้อง!",
    dndTitle: "โหมดห้ามรบกวน",
    dndDesc: "เปิดใช้งานโหมดห้ามรบกวนขณะเล่นเกม จำกัดการแจ้งเตือนและสายเรียกเข้า เพื่อให้คุณสามารถเล่นเกมได้โดยไม่ถูกรบกวน",
    permissionDeniedTitle: "สิทธิ์ถูกปฏิเสธ",
    permissionDeniedDesc: "โปรดเปิดใช้งาน API JavaScript สำหรับ Encore Tweaks ในการตั้งค่า MMRL; มิฉะนั้น WebUI นี้จะไม่สามารถทำงานได้",
    breadcrumbsSettings: "การตั้งค่า",
    breadcrumbsModules: "โมดูล & สิทธิ์",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "อนุญาต API ขั้นสูงของ KernelSU",
    editGamelistTitle: "แก้ไขรายการเกม",
    editGamelistDesc: "โปรไฟล์ประสิทธิภาพจะเปิดใช้งานเมื่อเปิดเกมหรือแอปใด ๆ ในรายการนี้",
    saveChanges: "บันทึกการเปลี่ยนแปลง",
    saveLogs: "บันทึกล็อกของโมดูล"
  },
  ko: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "현재 프로필",
    kernelTitle: "Kernel",
    chipsetTitle: "칩셋",
    androidSDKTitle: "Android SDK",
    settingsTitle: "설정",
    killLogger: "로거 중지",
    dndGameplay: "게임 중 방해 금지",
    defaultCpuGov: "기본 CPU 거버너",
    powersaveCpuGov: "절전 CPU 거버너",
    actionsTitle: "작업",
    supportTitle: "후원하기",
    supportDescription: "Encore Tweaks는 항상 무료로 제공됩니다. 하지만 기부를 통해 응원을 표시할 수 있습니다.",
    killLoggerTitle: "로거 중지",
    killLoggerDesc: "이 옵션은 로깅 서비스를 중지하고 로그 출력을 차단하여 성능 오버헤드를 줄입니다.",
    killLoggerWarning: "경고: logd 서비스에 의존하는 소프트웨어가 제대로 작동하지 않을 수 있습니다!",
    dndTitle: "방해 금지 모드",
    dndDesc: "게임 중 방해 금지 모드를 활성화하여 알림 및 통화 방해를 제한합니다.",
    permissionDeniedTitle: "권한 거부됨",
    permissionDeniedDesc: "MMRL 설정에서 Encore Tweaks의 JavaScript API를 활성화하세요. 그렇지 않으면 WebUI가 작동하지 않습니다.",
    breadcrumbsSettings: "설정",
    breadcrumbsModules: "모듈 및 권한",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "고급 KernelSU API 허용",
    editGamelistTitle: "게임 목록 수정",
    editGamelistDesc: "여기에 등록된 게임 또는 앱이 실행될 때 성능 프로필이 활성화됩니다.",
    saveChanges: "변경 사항 저장",
    cancelChanges: "변경 사항 취소",
    saveLogs: "모듈 로그 저장"
  },
  vi: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Cấu hình hiện tại",
    kernelTitle: "Kernel",
    chipsetTitle: "Chipset",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Cài đặt",
    killLogger: "Tắt Logger",
    dndGameplay: "DND khi chơi game",
    defaultCpuGov: "Bộ điều chỉnh CPU mặc định",
    powersaveCpuGov: "Bộ điều chỉnh CPU tiết kiệm năng lượng",
    actionsTitle: "Hành động",
    supportTitle: "Hỗ trợ tôi",
    supportDescription: "Encore Tweaks luôn miễn phí cho tất cả mọi người. Tuy nhiên, bạn có thể ủng hộ tôi bằng cách quyên góp.",
    killLoggerTitle: "Tắt Logger",
    killLoggerDesc: "Tùy chọn này sẽ dừng các dịch vụ ghi nhật ký và tắt log, giúp giảm tải hiệu suất.",
    killLoggerWarning: "CẢNH BÁO: Phần mềm phụ thuộc vào logd có thể không hoạt động đúng!",
    dndTitle: "Không làm phiền",
    dndDesc: "Bật chế độ không làm phiền khi chơi game. Hạn chế thông báo và cuộc gọi để bạn có thể chơi mà không bị gián đoạn.",
    permissionDeniedTitle: "Quyền bị từ chối",
    permissionDeniedDesc: "Vui lòng kích hoạt API JavaScript cho Encore Tweaks trong cài đặt MMRL; WebUI này sẽ không hoạt động nếu không có nó.",
    breadcrumbsSettings: "Cài đặt",
    breadcrumbsModules: "Module & Quyền",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Cho phép API KernelSU nâng cao",
    editGamelistTitle: "Chỉnh sửa danh sách trò chơi",
    editGamelistDesc: "Cấu hình hiệu suất sẽ được kích hoạt khi bất kỳ trò chơi hoặc ứng dụng nào trong danh sách này được mở.",
    saveChanges: "Lưu thay đổi",
    cancelChanges: "Hủy thay đổi",
    saveLogs: "Lưu nhật ký module"
  },
  hi: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "वर्तमान प्रोफ़ाइल",
    kernelTitle: "Kernel",
    chipsetTitle: "चिपसेट",
    androidSDKTitle: "Android SDK",
    settingsTitle: "सेटिंग्स",
    killLogger: "लॉगर बंद करें",
    dndGameplay: "गेमप्ले के दौरान DND",
    defaultCpuGov: "डिफ़ॉल्ट CPU गवर्नर",
    powersaveCpuGov: "पावर सेविंग CPU गवर्नर",
    actionsTitle: "क्रियाएँ",
    supportTitle: "मुझे समर्थन दें",
    supportDescription: "Encore Tweaks पूरी तरह से मुफ्त है और हमेशा रहेगा। लेकिन आप दान करके अपना समर्थन दिखा सकते हैं।",
    killLoggerTitle: "लॉगर बंद करें",
    killLoggerDesc: "यह विकल्प लॉगर सेवाओं को बंद कर देगा और लॉग को चुप करा देगा, जिससे प्रदर्शन में सुधार होगा।",
    killLoggerWarning: "चेतावनी: जो सॉफ़्टवेयर logd सेवा पर निर्भर है, वह सही से काम नहीं करेगा!",
    dndTitle: "डिस्टर्ब न करें",
    dndDesc: "गेम खेलते समय 'डू नॉट डिस्टर्ब' मोड सक्षम करें। यह नोटिफिकेशन और कॉल को सीमित करता है, जिससे आप बिना रुकावट के अपने पसंदीदा गेम खेल सकते हैं।",
    permissionDeniedTitle: "अनुमति अस्वीकृत",
    permissionDeniedDesc: "कृपया MMRL सेटिंग्स में Encore Tweaks के लिए JavaScript API सक्षम करें, अन्यथा यह WebUI काम नहीं करेगा।",
    breadcrumbsSettings: "सेटिंग्स",
    breadcrumbsModules: "मॉड्यूल और अनुमतियाँ",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "उन्नत KernelSU API की अनुमति दें",
    editGamelistTitle: "गेम सूची संपादित करें",
    editGamelistDesc: "जब यहां सूचीबद्ध गेम या ऐप्स चालू किए जाते हैं, तो प्रदर्शन प्रोफ़ाइल सक्रिय हो जाएगी।",
    saveChanges: "परिवर्तन सहेजें",
    cancelChanges: "परिवर्तन रद्द करें",
    saveLogs: "मॉड्यूल लॉग सहेजें"
  },
  ar: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "الملف الشخصي الحالي",
    kernelTitle: "Kernel",
    chipsetTitle: "مجموعة الشرائح",
    androidSDKTitle: "Android SDK",
    settingsTitle: "الإعدادات",
    killLogger: "إيقاف المسجل",
    dndGameplay: "عدم الإزعاج أثناء اللعب",
    defaultCpuGov: "المنظم الافتراضي للمعالج",
    powersaveCpuGov: "منظم توفير الطاقة للمعالج",
    actionsTitle: "الإجراءات",
    supportTitle: "ادعمني",
    supportDescription: "Encore Tweaks مجاني وسيبقى دائمًا مجانيًا. لكن يمكنك إظهار دعمك من خلال التبرع.",
    killLoggerTitle: "إيقاف المسجل",
    killLoggerDesc: "سيؤدي هذا الخيار إلى إيقاف خدمات التسجيل وكتم السجلات، مما يقلل من عبء الأداء.",
    killLoggerWarning: "تحذير: البرامج التي تعتمد على خدمة logd قد لا تعمل بشكل صحيح!",
    dndTitle: "عدم الإزعاج",
    dndDesc: "تفعيل وضع عدم الإزعاج أثناء اللعب. يحد من مقاطعات الإشعارات والمكالمات، مما يسمح لك باللعب بدون تشتيت.",
    permissionDeniedTitle: "تم رفض الإذن",
    permissionDeniedDesc: "يرجى تمكين واجهة برمجة تطبيقات JavaScript لـ Encore Tweaks في إعدادات MMRL، وإلا فلن يعمل هذا ال WebUI.",
    breadcrumbsSettings: "الإعدادات",
    breadcrumbsModules: "الوحدات والأذونات",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "السماح بواجهة برمجة KernelSU المتقدمة",
    editGamelistTitle: "تحرير قائمة الألعاب",
    editGamelistDesc: "سيتم تنشيط ملف الأداء عند تشغيل أي من الألعاب والتطبيقات المدرجة هنا.",
    saveChanges: "حفظ التغييرات",
    cancelChanges: "إلغاء التغييرات",
    saveLogs: "حفظ سجلات الوحدة"
  },
  es: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Perfil Actual",
    kernelTitle: "Kernel",
    chipsetTitle: "Chipset",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Configuración",
    killLogger: "Desactivar Logger",
    dndGameplay: "No Molestar en Juego",
    defaultCpuGov: "Governor de CPU Predeterminado",
    powersaveCpuGov: "Governor CPU Ahorro de Energía",
    actionsTitle: "Acciones",
    supportTitle: "Apóyame",
    supportDescription: "Encore Tweaks es y siempre será gratuito para todos. Sin embargo, puedes demostrar tu apoyo con una donación.",
    killLoggerTitle: "Desactivar Logger",
    killLoggerDesc: "Esta opción detendrá los servicios de registro y silenciará los logs, reduciendo la sobrecarga en el rendimiento.",
    killLoggerWarning: "¡ADVERTENCIA: El software que depende del servicio logd puede no funcionar correctamente!",
    dndTitle: "No Molestar",
    dndDesc: "Activa el modo 'No Molestar' al jugar. Reduce interrupciones de notificaciones y llamadas, permitiéndote jugar sin distracciones.",
    permissionDeniedTitle: "Permiso Denegado",
    permissionDeniedDesc: "Activa la API de JavaScript para Encore Tweaks en la configuración de MMRL; esta WebUI no funcionará sin ella.",
    breadcrumbsSettings: "Configuración",
    breadcrumbsModules: "Módulos y Permisos",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Permitir API Avanzada de KernelSU",
    editGamelistTitle: "Editar Lista de Juegos",
    editGamelistDesc: "El perfil de rendimiento se activará cuando se inicie cualquiera de los juegos o aplicaciones listados aquí.",
    saveChanges: "Guardar Cambios",
    cancelChanges: "Cancelar Cambios",
    saveLogs: "Guardar Registros del Módulo"
  },
  pl: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Aktualny Profil",
    kernelTitle: "Jądro",
    chipsetTitle: "Chipset",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Ustawienia",
    killLogger: "Wyłącz rejestrowanie",
    dndGameplay: "DND podczas Gry",
    defaultCpuGov: "Domyślny Governor CPU",
    powersaveCpuGov: "Oszczędny Governor CPU",
    actionsTitle: "Akcje",
    supportTitle: "Wesprzyj Mnie",
    supportDescription: "Encore Tweaks jest i zawsze będzie darmowy dla wszystkich. Możesz jednak okazać swoje wsparcie, dokonując darowizny.",
    killLoggerTitle: "Wyłącz rejestrowanie",
    killLoggerDesc: "Ta opcja zatrzyma usługi rejestrowania i wyciszy dzienniki, zmniejszając obciążenie wydajności.",
    killLoggerWarning: "OSTRZEŻENIE: Oprogramowanie zależne od usługi logd może nie działać poprawnie!",
    dndTitle: "Nie Przeszkadzać",
    dndDesc: "Włącza tryb 'Nie Przeszkadzać' podczas grania. Ogranicza zakłócenia ze strony powiadomień i połączeń, umożliwiając grę bez rozpraszania uwagi.",
    permissionDeniedTitle: "Brak Uprawnień",
    permissionDeniedDesc: "Aktywuj API JavaScript dla Encore Tweaks w ustawieniach MMRL; bez tego WebUI nie będzie działać.",
    breadcrumbsSettings: "Ustawienia",
    breadcrumbsModules: "Moduły i Uprawnienia",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Zezwól na Zaawansowane API KernelSU",
    editGamelistTitle: "Edytuj Listę Gier",
    editGamelistDesc: "Profil wydajności zostanie aktywowany po uruchomieniu dowolnej gry lub aplikacji z tej listy.",
    saveChanges: "Zapisz Zmiany",
    cancelChanges: "Anuluj Zmiany",
    saveLogs: "Zapisz Dzienniki Modułu"
  },
  tl: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Kasalukuyang Profile",
    kernelTitle: "Kernel",
    chipsetTitle: "Chipset",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Mga Setting",
    killLogger: "Ihinto ang Logger",
    dndGameplay: "DND sa Paglalaro",
    defaultCpuGov: "Default na CPU Governor",
    powersaveCpuGov: "Powersave na CPU Governor",
    actionsTitle: "Mga Aksyon",
    supportTitle: "Suportahan Mo Ako",
    supportDescription: "Ang Encore Tweaks ay, at palaging magiging, libre para sa iyo, at sa lahat. Gayunpaman, maaari mong ipakita na nagmamalasakit ka sa pamamagitan ng pagbibigay ng donasyon.",
    killLoggerTitle: "Ihinto ang Logger",
    killLoggerDesc: "Ang opsyong ito ay titigil sa mga serbisyo ng logger at papatahimikin ang mga log, kaya makakatulong ito sa pagpapababa ng paggamit ng system resources at pagpapahusay ng performance.",
    killLoggerWarning: "BABALA: Ang mga software na nangangailangan ng logd service ay maaaring hindi gumana nang maayos!",
    dndTitle: "Do Not Disturb",
    dndDesc: "I-enable ang mode na 'Do Not Disturb' kapag naglalaro ng mga laro. Nililimitahan ang mga pagpapatigil mula sa mga notification at tawag, na nagpapahintulot sa iyo na maglaro ng iyong mga paboritong laro nang walang anumang pagkaabala.",
    permissionDeniedTitle: "Pahintulot Tinanggihan",
    permissionDeniedDesc: "Paki-activate ang JavaScript API para sa Encore Tweaks sa mga setting ng MMRL; ang WebUI na ito ay hindi gagana nang wala ito.",
    breadcrumbsSettings: "Mga Setting",
    breadcrumbsModules: "Mga Module at Pahintulot",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Pahintulutan ang Advanced na KernelSU API",
    editGamelistTitle: "I-edit ang Gamelist",
    editGamelistDesc: "Ang performance profile ay maa-activate kapag ang alinman sa mga laro at apps na nakalista dito ay inilunsad.",
    saveChanges: "I-save ang mga Pagbabago",
    cancelChanges: "Kanselahin ang mga Pagbabago",
    saveLogs: "I-save ang mga Log ng Module"
  },
  ro: {
    moduleTitle: "Encore Tweaks",
    profileTitle: "Profil Curent",
    kernelTitle: "Kernel",
    chipsetTitle: "Chipset",
    androidSDKTitle: "Android SDK",
    settingsTitle: "Setări",
    killLogger: "Dezactivează Logger-ul",
    dndGameplay: "DND în Jocuri",
    defaultCpuGov: "Guvernator CPU Implicit",
    powersaveCpuGov: "Guvernator CPU Economisire Energie",
    actionsTitle: "Acțiuni",
    supportTitle: "Susține-mă",
    supportDescription: "Encore Tweaks este și va fi întotdeauna gratuit pentru tine și pentru toată lumea. Totuși, poți arăta că îți pasă făcând o donație.",
    killLoggerTitle: "Dezactivează Logger-ul",
    killLoggerDesc: "Această opțiune va opri serviciile de logare și va dezactiva logurile, reducând astfel consumul de resurse.",
    killLoggerWarning: "AVERTISMENT: Software-ul care depinde de serviciul logd nu va funcționa corect!",
    dndTitle: "Nu Deranja",
    dndDesc: "Activează modul „Nu deranja” în timpul jocurilor. Limitează întreruperile cauzate de notificări și apeluri, permițându-ți să te bucuri de jocuri fără distrageri.",
    permissionDeniedTitle: "Permisiune Refuzată",
    permissionDeniedDesc: "Te rugăm să activezi API-ul JavaScript pentru Encore Tweaks în setările MMRL; această interfață web nu va funcționa fără el.",
    breadcrumbsSettings: "Setări",
    breadcrumbsModules: "Module & Permisiuni",
    breadcrumbsEncore: "Encore Tweaks",
    breadcrumbsAllowAPI: "Permite API-ul Avansat KernelSU",
    editGamelistTitle: "Editează Lista de Jocuri",
    editGamelistDesc: "Profilul de performanță va fi activat când oricare dintre jocurile sau aplicațiile listate aici este lansat.",
    saveChanges: "Salvează Modificările",
    cancelChanges: "Anulează Modificările",
    saveLogs: "Salvează Logurile Modulului"
  }
};

/**
 * Function to update the translation of all elements with data-i18n attribute
 * @param {string} lang - language code (e.g., 'en' or 'ru')
 */
function translatePage(lang) {
  document.documentElement.lang = lang;
  
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    // Fallback to English if key is missing
    const text = translations[lang]?.[key] || translations.en[key] || key;
    el.innerText = text;
  });

  // Update buttons with fallback
  const editGamelistBtn = document.getElementById('edit_gamelist_btn');
  if (editGamelistBtn) {
    editGamelistBtn.innerText = translations[lang]?.editGamelistTitle || translations.en.editGamelistTitle;
  }

  const restartDaemonBtn = document.getElementById('restart_daemon_btn');
  if (restartDaemonBtn) {
    restartDaemonBtn.innerText = translations[lang]?.restartDaemon || translations.en.restartDaemon;
  }

  const saveLogBtn = document.getElementById('save_log_btn');
  if (saveLogBtn) {
    saveLogBtn.innerText = translations[lang]?.saveLogs || translations.en.saveLogs;
  }
}

// Check localStorage for saved language
let savedLang = localStorage.getItem('selectedLanguage');
let pageLang;

if (savedLang && translations.hasOwnProperty(savedLang)) {
  pageLang = savedLang;
} else {
  // Fallback to browser language or English
  const browserLang = navigator.language.split('-')[0];
  pageLang = translations.hasOwnProperty(browserLang) ? browserLang : 'en';
}

// Set the selected language in the language selector
const languageSelector = document.getElementById('languageSelector');
if (languageSelector) {
  languageSelector.value = pageLang;
}

// Apply translation on page load
translatePage(pageLang);

// Handle language change by the user
if (languageSelector) {
  languageSelector.addEventListener('change', (e) => {
    const lang = e.target.value;
    localStorage.setItem('selectedLanguage', lang); // Save to localStorage
    translatePage(lang);
  });
}
