/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "var(--primary, #FFB3AE)",
        "on-primary": "var(--onPrimary, #571E1C)",
        "primary-container": "var(--primaryContainer, #733330)",
        "on-primary-container": "var(--onPrimaryContainer, #FFDAD7)",
        "inverse-primary": "var(--inversePrimary, #904A46)",
        "secondary": "var(--secondary, #E7BDB9)",
        "on-secondary": "var(--onSecondary, #442927)",
        "secondary-container": "var(--secondaryContainer, #5D3F3D)",
        "on-secondary-container": "var(--onSecondaryContainer, #FFDAD7)",
        "tertiary": "var(--tertiary, #E2C28C)",
        "on-tertiary": "var(--onTertiary, #402D04)",
        "tertiary-container": "var(--tertiaryContainer, #594319)",
        "on-tertiary-container": "var(--onTertiaryContainer, #FFDEA6)",
        "background": "var(--background, #1A1111)",
        "on-background": "var(--onBackground, #F1DEDD)",
        "surface": "var(--surface, #1A1111)",
        "on-surface": "var(--onSurface, #F1DEDD)",
        "surface-variant": "var(--surfaceVariant, #534342)",
        "on-surface-variant": "var(--onSurfaceVariant, #D8C2BF)",
        "surface-tint": "var(--surfaceTint, #FFB3AE)",
        "inverse-surface": "var(--inverseSurface, #F1DEDD)",
        "inverse-on-surface": "var(--inverseOnSurface, #382E2D)",
        "error": "var(--error, #FFB4AB)",
        "on-error": "var(--onError, #690005)",
        "error-container": "var(--errorContainer, #93000A)",
        "on-error-container": "var(--onErrorContainer, #FFDAD6)",
        "outline": "var(--outline, #A08C8A)",
        "outline-variant": "var(--outlineVariant, #534342)",
        "scrim": "var(--scrim, #000000)",
        "surface-bright": "var(--surfaceBright, #423736)",
        "surface-dim": "var(--surfaceDim, #1A1111)",
        "surface-container": "var(--surfaceContainer, #271D1D)",
        "surface-container-high": "var(--surfaceContainerHigh, #322827)",
        "surface-container-highest": "var(--surfaceContainerHighest, #3D3231)",
        "surface-container-low": "var(--surfaceContainerLow, #231919)",
        "surface-container-lowest": "var(--surfaceContainerLowest, #140C0B)",
        "filled-tonal-button-content-color": "var(--filledTonalButtonContentColor)",
        "filled-tonal-button-container-color": "var(--filledTonalButtonContainerColor)",
        "filled-tonal-button-disabled-content-color": "var(--filledTonalButtonDisabledContentColor)",
        "filled-tonal-button-disabled-container-color": "var(--filledTonalButtonDisabledContainerColor)",
        "filled-card-content-color": "var(--filledCardContentColor)",
        "filled-card-container-color": "var(--filledCardContainerColor)",
        "filled-card-disabled-content-color": "var(--filledCardDisabledContentColor)",
        "filled-card-disabled-container-color": "var(--filledCardDisabledContainerColor)",
      },
    },
  },
  plugins: [require("daisyui")],
};
