name: Build Encore Tweaks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - '.github/scripts/**'
      - 'java/**'
      - 'jni/**'
      - 'scripts/**'
      - 'module/**'
      - 'webui/**'
      - 'gamelist.txt'
      - 'version'

# Allow only one concurrent build workflows
concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    name: Build Flashable Zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: NDK Setup
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r29

      - name: JDK Setup
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "temurin"

      - name: Bun Setup
        uses: oven-sh/setup-bun@v2

      - name: Build Encore Daemon
        run: ndk-build -j$(nproc --all)

      - name: Compile Java
        working-directory: java
        run: |
          ANDROID_JAR="$ANDROID_HOME/platforms/android-34/android.jar"
          BUILD_TOOLS_DIR=$(ls -d $ANDROID_HOME/build-tools/* | sort -V | tail -n 1)
          D8_TOOL="$BUILD_TOOLS_DIR/d8"
          javac -cp "$ANDROID_JAR" SystemMonitor.java
          "$D8_TOOL" SystemMonitor.class --lib "$ANDROID_JAR" --output .
          mv classes.dex system_monitor.dex

      - name: Build WebUI
        working-directory: webui
        run: |
          bun install
          bun run build
          cp -r ./dist/* ../module/webroot

      - name: Compile Flashable Zip
        id: compileZip
        run: bash .github/scripts/compile_zip.sh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: encore-build
          path: ${{ steps.compileZip.outputs.zipName }}

      - name: Upload To Telegram
        if: env.CHAT_ID != '' && env.BOT_TOKEN != ''
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          TITLE: Encore Tweaks
        run: |
          export VERSION=$(git rev-list --count HEAD)
          bash .github/scripts/telegram_bot.sh ${{ steps.compileZip.outputs.zipName }}
